 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/apartments", type: :request do
  
  # Apartment. As you add validations to Apartment, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Apartment.create! valid_attributes
      get apartments_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      apartment = Apartment.create! valid_attributes
      get apartment_url(apartment)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_apartment_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      apartment = Apartment.create! valid_attributes
      get edit_apartment_url(apartment)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Apartment" do
        expect {
          post apartments_url, params: { apartment: valid_attributes }
        }.to change(Apartment, :count).by(1)
      end

      it "redirects to the created apartment" do
        post apartments_url, params: { apartment: valid_attributes }
        expect(response).to redirect_to(apartment_url(Apartment.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Apartment" do
        expect {
          post apartments_url, params: { apartment: invalid_attributes }
        }.to change(Apartment, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post apartments_url, params: { apartment: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested apartment" do
        apartment = Apartment.create! valid_attributes
        patch apartment_url(apartment), params: { apartment: new_attributes }
        apartment.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the apartment" do
        apartment = Apartment.create! valid_attributes
        patch apartment_url(apartment), params: { apartment: new_attributes }
        apartment.reload
        expect(response).to redirect_to(apartment_url(apartment))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        apartment = Apartment.create! valid_attributes
        patch apartment_url(apartment), params: { apartment: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested apartment" do
      apartment = Apartment.create! valid_attributes
      expect {
        delete apartment_url(apartment)
      }.to change(Apartment, :count).by(-1)
    end

    it "redirects to the apartments list" do
      apartment = Apartment.create! valid_attributes
      delete apartment_url(apartment)
      expect(response).to redirect_to(apartments_url)
    end
  end
end
